# Generated by Django 6.0 on 2025-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_warrantyregistration_delete_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyregistration',
            name='asset_name',
            field=models.CharField(default='Unknown Asset', max_length=255),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
